apiVersion: 1

datasources:
  - name: MongoDB-Academic-Integrity
    type: grafana-mongodb-datasource
    uid: mongodb
    access: proxy
    url: mongodb://admin:admin123@mongodb:27017/academic_integrity
    isDefault: false
    editable: true
    jsonData:
      authType: "credentials"
      defaultDatabase: "academic_integrity"
      tlsSkipVerify: true
